### ISSUE TITLE
Reducing the amount of weeks planned breaks API

### ISSUE THREAD

**Issue by matheuscodes** [matheuscodes/aaa-app#1]
Changing the end date to remove a week from the goal plan causes the API to throw an error.

```
java.sql.SQLException: Parameter index out of range (3 > number of parameters, which is 2).
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963) ~[mysql-connector-java-5.1.39.jar:5.1.39]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896) ~[mysql-connector-java-5.1.39.jar:5.1.39]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885) ~[mysql-connector-java-5.1.39.jar:5.1.39]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[mysql-connector-java-5.1.39.jar:5.1.39]
```

**Comment by matheuscodes** [comment]
Verified on production https://github.com/matheuscodes/aaa-app/commit/88302f8b4e92434ddf540a888762a76d21d6ee0f

**Comment by matheuscodes** [comment]
Was purely Hibernate configuration issue.
